version: "3"
services:
  content_image_optimization_kf:
    image: "content_image_optimization_kf"
    # pull_policy: always
    build: .
    container_name: content_image_optimization_kf
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids:
              #   - MIG-60d6a708-f1b0-54b0-83a0-2b396432327b
              #   - MIG-71db94d9-df33-5a82-82b8-76c07dfbc45b
              capabilities: [gpu]
    ports:
      - "5008:5008"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - SERVER_IP=103.42.50.120
      - PROCESS=image_enhancement
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/ubuntu/kashif/content_image_optimization/api:/opt/api:rw
      - /var/log/images/ml_models:/var/log/images/ml_models:rw
      - /home/ubuntu/kashif/image_enhancement:/home/ubuntu/kashif/image_enhancement:rw
    runtime: nvidia

    tty: true

